name: Publish package to test.pypi.org

on:
  workflow_dispatch:

jobs:
  pypi-publish:
    runs-on: ubuntu-22.04

    environment:
      name: testpypi
      url: https://test.pypi.org/p/pydantic2zod

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3.3.0

      - uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Publish a package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
