name: QA checks

on: push

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        pydantic_versions: ["< 2", ">= 2"]
        task:
          - check_types
          - check_fmt
          - test

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"

      - uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "1.8.4"

      - name: Install dependencies
        run: |
          poetry install
          poetry run pip install "pydantic ${{ matrix['pydantic_versions'] }}"

      - name: QA
        run: poetry run task ${{ matrix['task'] }}
